### ISSUE TITLE
Replace gitter icon with twitter icon

### ISSUE THREAD

**Issue by czgdp1807** [rtrclubiitj/rtrclubiitj.github.io#11]
**Describe the bug/feature**

Currently, we show gitter icon in the navigation bar/footer of the website, which is serving no purpose since, development of the website is of no use to a common rotaractor. So it would be better to replace the gitter icon with twitter icon.

**To Reproduce(for bug)**

**Screenshots(for bug)**

As can be seen the gitter icon in the rightmost end of the navigation bar. That should be replaced with twitter icon.
![Screenshot from 2019-08-15 22-26-36](https://user-images.githubusercontent.com/36567889/63111656-c95ae180-bfab-11e9-8620-af865c149b2f.png)
![Screenshot from 2019-08-15 22-28-14](https://user-images.githubusercontent.com/36567889/63111755-feffca80-bfab-11e9-93a6-f5f8d0d9c9e5.png)
![Screenshot from 2019-08-15 22-27-55](https://user-images.githubusercontent.com/36567889/63111766-03c47e80-bfac-11e9-8617-19ede85de301.png)

**Device Details(for bug)**

**Other Comments**

@asharani97 Can you please fix this issue?

**Comment by czgdp1807** [comment]
@asharani97 Any updates/news? Are you working on it?

**Comment by asharani97** [comment]
Yes , I m working on it.. will update you

**Comment by asharani97** [comment]
its done
