### ISSUE TITLE
Add blog entry for minutes of meetings

### ISSUE THREAD

**Issue by czgdp1807** [rtrclubiitj/rtrclubiitj.github.io#12]
**Describe the bug/feature**

Blog entry for the minutes of meetings have to be added. The meeting was held a few days back with the officials of our parent club.

**To Reproduce(for bug)**

**Screenshots(for bug)**

**Device Details(for bug)**

**Other Comments**

The content is in the file given below.
[board_meeting.txt](https://github.com/rtrclubiitj/rtrclubiitj.github.io/files/3506463/board_meeting.txt)

@Saptashrungi Please do the needful, probably before the next meeting.

**Comment by czgdp1807** [comment]
ping @Saptashrungi Any news/updates? Have you started working on it?

**Comment by Saptashrungi** [comment]
I haven't started on this one. Will add by tomorrow morning or tonight.
