### ISSUE TITLE
Limit the maximum width of textbox

### ISSUE THREAD

**Issue by czgdp1807** [rtrclubiitj/rtrclubiitj.github.io#24]
**Describe the bug/feature**

The maximum width of the text box in the contact form at the footer should be limited. 

**To Reproduce(for bug)**

1. Go to the contact form at the footer of https://rtrclubiitj.github.io/
2. Stretch the text box by holding the bottom right corner of the text box labelled as `Message`. 
3. You will observe that three white lines appear going outside the boundary into the background.

**Screenshots(for bug)**

![bug](https://user-images.githubusercontent.com/36567889/63520864-0e829480-c513-11e9-8cdd-b5396dddbe0e.png)

**Device Details(for bug)**

Use desktop for observing the bug more clearly. Check on mobile width too by adjusting the browser screen on your desktop.

**Other Comments**

@asharani97 Please fix this issue.

**Comment by czgdp1807** [comment]
@asharani97 Any updates on this?

**Comment by asharani97** [comment]
working
