### ISSUE TITLE
Add previous information of the club

### ISSUE THREAD

**Issue by czgdp1807** [rtrclubiitj/rtrclubiitj.github.io#25]
**Describe the bug/feature**

The information about the former board of directors of the club should be there. A separate page should be created having url something like, `https://rtrclubiitj.github.io/former_boards`.

**To Reproduce(for bug)**

**Screenshots(for bug)**

**Device Details(for bug)**

**Other Comments**

@Saptashrungi Please fix this issue.

**Comment by Saptashrungi** [comment]
Will fix soon.. Tonight

**Comment by Saptashrungi** [comment]
From where will I get information about former board of directors?

**Comment by czgdp1807** [comment]
I have asked about it in the group. Well make a new PR so that the website looks like the one [here](https://codezonediitj.github.io/), i.e., there should be a third tab, named, `Former Boards`(keep it empty). It can be filled when the information will be available.

**Comment by Saptashrungi** [comment]
Okay
