### ISSUE TITLE
Remove About page

### ISSUE THREAD

**Issue by czgdp1807** [rtrclubiitj/rtrclubiitj.github.io#5]
Details regarding about page in https://github.com/rtrclubiitj/rtrclubiitj.github.io/pull/4
Probably, the page isn't built properly by github pages.
Now, there are two solutions, one temporary and one long term.
The temporary solution is to remove the about page and instead of that add a blog entry for the structure of the club. 
The long term solution is to change the jekyll theme. Currently, we are using `jasper2` which seems to buggy and rigid. Instead I think `massively` is a better option. Refer, https://codezonediitj.github.io/ for the demo. It can be easily done, but will require a lot of efforts.

**Comment by czgdp1807** [comment]
Currenty, the short term solution seems good.

**Comment by czgdp1807** [comment]
**Deadline**
Please try to do it, by tomorrow evening.

**Comment by Saptashrungi** [comment]
Okay will do it tonight
